### ISSUE TITLE
Support for Theben Conexa SMGWs

### ISSUE THREAD

**Issue by klacol** [jannickfahlbusch/ha-ppc-smgw#26]
Hi, great extension here. I love the idea, to make the data from the Smart Meter Gateways available in HA.

My question is: Is this extension supposed to support "only" the Gateway from PPC? The title of the repos imposes that.

I have a Theben Conexa 3.0 and tried to use it in this extension. It does not work out of the box, because the API's are different. But the main architecture is very similar. Since all Smart Meter Gateways can be used with the software [Trudi](https://bitbucket.org/dzgtrudi/trudi-public/src/master/), it seems to mee, that they all share the same set of sensors. But the way, they are retrieved is specific for each type of gateway. So, it perhaps the specific implementation could derive from a general class, or so.

**Comment by klacol** [comment]
I have asked the manufacturer of my Smart Meter Gateways (Theben Smart Energy GmbH) and they were very friendly and sent me the interface manual for the device (Connexa 3.0) in german langage:.

[Schnittstellenbeschreibung IF_GW_CON.pdf](https://github.com/user-attachments/files/18307786/Schnittstellenbeschreibung.IF_GW_CON.pdf)

With this help it works like a charm to connect to the API. I have just written some line of codes, quick and dirty. I would work something like this:


```python
class ThebenConnexaClient:
    def __init__(self, base_url, username, password):
        self.base_url = base_url
        self.session = requests.Session()
        self.session.auth = HTTPDigestAuth(username, password)
        self.session.verify = False
        self.session.headers.update({'Content-Type': 'application/json'})  # Setzt den Content-Type Header

    def post_endpoint(self, endpoint, data):
        url = f"{self.base_url}/{endpoint}"
        response = self.session.post(url, json=data)
        if response.status_code == 200:
            responseData = DotMap(json.loads(response.text))
            return Result.Ok(responseData) 
        else:
            return Result.Error(f'Fehler {response}.')
  
    # Abruf von Informationen über das Smart Meter Gateway durch den Letztverbraucher (A-2.2)
    def get_smgw_info(self):
        data = { "method" : "smgw-info" }  
        result = self.post_endpoint('smgw/m2m',data)
        if result.success:
            return Result.Ok(result.value["smgw-info"])
        else:
            return result

    # Abruf der gesamten Vertragsdaten des Letztverbrauchers (A-2.3)
    def get_user_info(self):
        data = { "method" : "user-info" }  
        result = self.post_endpoint('smgw/m2m',data)
        if result.success:
            return Result.Ok(result.value["user-info"])
        else:
            return result

    # Abruf von Informationen eines Vertrages durch den Letztverbraucher. (A-2.4)
    # Dient dazu die Daten über die Daten eines einzelnen Vertrages abzurufen.
    # contract_id: Ausgewählter Vertrag. Kann über get_user_info abgerufen werden.
    # database: Optional: Die zu lesende Messwertliste. Wenn nicht angegeben werden die Werte von allen Messwertlisten zurückgeliefert.
    #           Mögliche Werte sind: 
    #               origin: Die Originäre Messwertliste 
    #               derived: Die Abgeleitete Messwertliste
    #               calculated: Nur bei TAF2: Tarifumschaltmesswertliste 
    #               daily: Liste der Tageswerte
    def get_contract_info(self, usage_point_id,database=None):
        valid_databases = {"origin", "derived", "calculated", "daily"}   
        if database and database not in valid_databases:
            raise ValueError(f"Ungültiger Wert für database: {database}. Erlaubte Werte sind: {', '.join(valid_databases)}")
        data = { 
                    "method" : "usage-point-info", 
                    "usage-point-id" : usage_point_id                 
                }
        if database:
            data["database"] = database   #Optional
        return self.post_endpoint('smgw/m2m', data)
```

This is sample code for three of seven use cases, that are described in the document.

**Comment by jannickfahlbusch** [comment]
Hi,

thank you for the idea, generally this sounds like a reasonable approach to me. 
Can you confirm that Theben really offers an API with all the required information?

I'll have a look at this during the weekend to check how this could be implemented

**Comment by jannickfahlbusch** [comment]
@klacol could you check if the Theben maybe already implemented version 2.0 of TR-03109-1?

[This would be the documentation](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03109/TR-03109-1_Anlage_2_Webservices_v2_0.pdf?__blob=publicationFile&v=3), the BSI also [provides OpenAPI docs here](https://han-api.smgw.biz/docs)

**Comment by klacol** [comment]
The Release 2.0 of the API seems to be just a plan as of today.  My SMGW has not yet those endpoints, IMHO.

I have just checked the docs of the endpoint [/smgw/con/v1/exp/RegMtrReading/{meter_id}](https://han-api.smgw.biz/docs#/ConServices/Export_Reg_Meter_Reading_smgw_con_v1_exp_RegMtrReading__meter_id__get). It seems to be like a wrapper around the [OBIS-Kennzahlen](https://de.wikipedia.org/wiki/OBIS-Kennzahlen). That are definitions of properties that will be retrievable via the endpoint.

**Comment by Crockers1988** [comment]
Hi,

Is there any news about the integration of the Theben Connexa 3.0 SMGW?

I would be very happy to finally make the SMGW data visible in the dashboard of my HomeAssistant.

Best regards,

**Comment by klacol** [comment]
Hi @Crockers1988 , @JosefinBerlin 

Too much work this spring. I do not find time at the weekends to publish this with more info :-).

**Comment by jannickfahlbusch** [comment]
Hi all,

quick update: I finally found some time to start the implementation for additional manufacturers. You can find the current state in #33.

Right now I have introduced an interface that should make it relatively easy to add further manufacturers in the future. 
The Theben client is currently empty as I don't have a meter to test (I'll try to adapt the code from @klacol to start with).

I didn't bother with [config entry migration](https://developers.home-assistant.io/docs/config_entries_config_flow_handler#config-entry-migration) for now - but that shouldn't matter for new usages.

**Comment by klacol** [comment]
Hi @jannickfahlbusch, great. I am unsure, if i can test it and give feedback at this point. If yes, how would i have to install the integration?

**Comment by jannickfahlbusch** [comment]
I hope to find some time over the weekend to implement the actual client coding. Right now I've implemented the migration, the support for multiple vendors/devices but had no time for the actual code that fetches the data.

Once that is available in the branch I can ping you with instructions for the testing :)

**Comment by JosefinBerlin** [comment]
Hallo an alle,
mir ist es mittlerweile gelungen, über postman von Theben Conexa 3.0 alle Informationen gemäß Schnittstellenbeschreibung A-2.1 bis A-2.7 zu erhalten

**Comment by Crockers1988** [comment]
Hello everyone, 

if the integration is ready, I would also be willing to test it. Thanks for your work.

**Comment by jannickfahlbusch** [comment]
I just pushed [`v0.0.12-alpha1`](https://github.com/jannickfahlbusch/ha-ppc-smgw/releases/tag/v0.0.12-alpha1) as a pre-release, which should now at least be able to retrieve the firmware version of the Theben GWs.

Would somebody of you able to install this alpha version and paste the debug logs of it here?
For the debug logs you'll need this configuration in HAs `configuration.yaml`:
https://github.com/jannickfahlbusch/ha-ppc-smgw/blob/f6913402e0f14e5228971406d1dab057e8b6d68c/config/configuration.yaml#L6-L9

**Comment by JosefinBerlin** [comment]
Ich will es versuchen.

**Comment by JosefinBerlin** [comment]
Oh, ich muss leider feststellen, dass meine Kenntnisse nicht ausreichen. Die Protokollierung konnte ich noch in die configuration.yaml eintragen. Die Zip-Datei der Alpha-Version habe ich heruntergeladen und auf meinem Desktop entpackt. Dort liegt nun der Ordner ha-ppc-smgw-0.0.12-alpha1.  Wohin muss aber in homeassistant dieser Ordner? homeassistant > custom_components?
Oder geht der Weg ganz anders? Die Warnung hat mich etwas erschreckt.

**Comment by JosefinBerlin** [comment]
Habe mich aber jetzt doch getraut. Hier das Debug-Protokoll (sensible Daten ausgeXXXt):
2025-03-29 12:44:18.097 DEBUG (MainThread) [custom_components.ppc_smgw.config_flow] Connection Info called with {'name': 'Smart Meter Gateway Theben', 'host': 'https://192.168.178.XXX', 'username': '67070XXXX', 'password': 'XXXXXX', 'scan_interval': 5, 'debug': True}
2025-03-29 12:44:18.097 DEBUG (MainThread) [custom_components.ppc_smgw.config_flow] user_input: {'name': 'Smart Meter Gateway Theben', 'host': 'https://192.168.178.XXX', 'username': '67070XXXX', 'password': 'XXXXXX', 'scan_interval': 5, 'debug': True}
2025-03-29 12:44:18.099 INFO (MainThread) [homeassistant.setup] Setting up ppc_smgw
2025-03-29 12:44:18.100 DEBUG (MainThread) [custom_components.ppc_smgw] Vendor is: Vendor.Theben (<enum 'Vendor'>)
2025-03-29 12:44:18.100 DEBUG (MainThread) [custom_components.ppc_smgw] Initializing Theben client
2025-03-29 12:44:18.100 DEBUG (MainThread) [custom_components.ppc_smgw.coordinator] Fetching data from API
2025-03-29 12:44:18.100 INFO (MainThread) [custom_components.ppc_smgw] Getting data
2025-03-29 12:44:18.101 DEBUG (MainThread) [custom_components.ppc_smgw] Debugging enabled, returning fake data
2025-03-29 12:44:33.102 DEBUG (MainThread) [custom_components.ppc_smgw.coordinator] Finished fetching ppc_smgw data in 15.002 seconds (success: True)
2025-03-29 12:44:33.141 INFO (MainThread) [homeassistant.components.button] Setting up ppc_smgw.button
2025-03-29 12:44:33.141 DEBUG (MainThread) [custom_components.ppc_smgw.entity] Initializing restart_gateway. EntryID: 01JQGVF3NJ96PF1EB477XPA3MC
2025-03-29 12:44:33.142 DEBUG (MainThread) [custom_components.ppc_smgw.button] Adding button entities: <entity unknown.unknown=unknown>
2025-03-29 12:44:33.145 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new button.ppc_smgw entity: button.01jqgvf3nj96pf1eb477xpa3mc_restart_gateway
2025-03-29 12:44:33.152 INFO (MainThread) [homeassistant.components.sensor] Setting up ppc_smgw.sensor
2025-03-29 12:44:33.153 DEBUG (MainThread) [custom_components.ppc_smgw.entity] Initializing 1-0:1.8.0. EntryID: 01JQGVF3NJ96PF1EB477XPA3MC
2025-03-29 12:44:33.154 DEBUG (MainThread) [custom_components.ppc_smgw.entity] Initializing 1-0:2.8.0. EntryID: 01JQGVF3NJ96PF1EB477XPA3MC
2025-03-29 12:44:33.154 DEBUG (MainThread) [custom_components.ppc_smgw.entity] Initializing last_update. EntryID: 01JQGVF3NJ96PF1EB477XPA3MC
2025-03-29 12:44:33.160 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ppc_smgw entity: sensor.01jqgvf3nj96pf1eb477xpa3mc_1_0_1_8_0
2025-03-29 12:44:33.162 DEBUG (MainThread) [custom_components.ppc_smgw.sensor] Data: Information(readings={'1-0:1.8.0': Reading(value='724.9204', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Verbrauch Zählerstand', obis='1-0:1.8.0'), '1-0:2.8.0': Reading(value='3.0557', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Erzeugung Zählerstand', obis='1-0:2.8.0')}, firmware_version='1337-version', last_update=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>))
2025-03-29 12:44:33.167 DEBUG (MainThread) [custom_components.ppc_smgw.sensor] Data: Information(readings={'1-0:1.8.0': Reading(value='724.9204', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Verbrauch Zählerstand', obis='1-0:1.8.0'), '1-0:2.8.0': Reading(value='3.0557', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Erzeugung Zählerstand', obis='1-0:2.8.0')}, firmware_version='1337-version', last_update=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>))
2025-03-29 12:44:33.169 DEBUG (MainThread) [custom_components.ppc_smgw.sensor] Data: Information(readings={'1-0:1.8.0': Reading(value='724.9204', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Verbrauch Zählerstand', obis='1-0:1.8.0'), '1-0:2.8.0': Reading(value='3.0557', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Erzeugung Zählerstand', obis='1-0:2.8.0')}, firmware_version='1337-version', last_update=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>))
2025-03-29 12:44:33.170 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ppc_smgw entity: sensor.01jqgvf3nj96pf1eb477xpa3mc_1_0_2_8_0
2025-03-29 12:44:33.171 DEBUG (MainThread) [custom_components.ppc_smgw.sensor] Data: Information(readings={'1-0:1.8.0': Reading(value='724.9204', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Verbrauch Zählerstand', obis='1-0:1.8.0'), '1-0:2.8.0': Reading(value='3.0557', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Erzeugung Zählerstand', obis='1-0:2.8.0')}, firmware_version='1337-version', last_update=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>))
2025-03-29 12:44:33.176 DEBUG (MainThread) [custom_components.ppc_smgw.sensor] Data: Information(readings={'1-0:1.8.0': Reading(value='724.9204', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Verbrauch Zählerstand', obis='1-0:1.8.0'), '1-0:2.8.0': Reading(value='3.0557', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Erzeugung Zählerstand', obis='1-0:2.8.0')}, firmware_version='1337-version', last_update=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>))
2025-03-29 12:44:33.177 DEBUG (MainThread) [custom_components.ppc_smgw.sensor] Data: Information(readings={'1-0:1.8.0': Reading(value='724.9204', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Verbrauch Zählerstand', obis='1-0:1.8.0'), '1-0:2.8.0': Reading(value='3.0557', unit='kWh', timestamp=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>), isvalid='1', name='Elektro Wirkarbeit Erzeugung Zählerstand', obis='1-0:2.8.0')}, firmware_version='1337-version', last_update=datetime.datetime(2024, 12, 20, 16, 0, 1, tzinfo=<UTC>))
2025-03-29 12:44:33.178 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.ppc_smgw entity: sensor.01jqgvf3nj96pf1eb477xpa3mc_last_update

**Comment by JosefinBerlin** [comment]
Ich glaube, doch etwas falsch gemacht zu haben. Denn die Daten wären:

Firmware: v3.80.0-cc
M2M-Interface: 1.3.0

**Comment by klacol** [comment]
Thank you @jannickfahlbusch . I gave it a try. My steps are so:

1. Update the integration to version ``v0.0.12-alpha1`` via HACS

![Image](https://github.com/user-attachments/assets/3ab4edd4-3ee7-48e3-8171-1203de88bb3d)

2. Add a new device on the page http://homeassistant.local:8123/config/devices/dashboard

Great to see here the options for the different manufacturers:

![Image](https://github.com/user-attachments/assets/21530636-0477-41cc-b503-844cdaa3ebe5)

3. Added the following configuration for my smart meter gateway:

| Config   |    Value                                                         |
|-----------|-----------------------------------------------|
| Display Name | Theben Smart Energy Connexa 3.0    |
| URL to the PPC SMGW | https://10.11.120.2 (the IP is reachable from my local PC and from home assistant)  |
| Username | The username for the SMGW, that i got from my ``Messstellenbetreiber`` (works with TRUDI) | 
| Password | The password for the SMGW, that i got from my ``Messstellenbetreiber`` (works with TRUDI)  |
| Polling Intervall in Minutes |      1 | 
| Development mode |  not checked  |


After this step i get the message ``already_configured`` in the dialogue. How can I delete the previously configured device?

**Comment by klacol** [comment]
I think, I have configured the wrong URL

1. Which URL do I have to put into the configuration?
2. Do you accept the not valid TLS certificate?
3. It would be good to mask the username and the password in the log. (I have checked them in the log, they are correct, as configured, unfortunately, they do not give us the possibility to change it, asaik)

**Comment by klacol** [comment]
Ok, I have to look myself into this [file](https://github.com/jannickfahlbusch/ha-ppc-smgw/blob/thebenConnexaSupport/custom_components/ppc_smgw/gateways/theben/thebenconnexa/thebenconnexa.py) and figure out, how this kann work with my device locally.

**Comment by klacol** [comment]
In my samples i use the lib [``requests``](https://pypi.org/project/requests/). The integration uses the lib [``httpx``](https://pypi.org/project/httpx/).

My connection with ``requests`` works like a charm. But I cannot figure it out, how to connect to the Theben Connexa SMGW with ``httpx``.

I always get ``01 Unauthorized``. I have tried to retrieve the the information of the SMGW with this code:

```python
    # Request the smgw-info
    url = "https://10.11.120.2/smgw/m2m"
    username = "*****"
    password = "*****"
    body = {"method": "smgw-info"}

    client = httpx.Client(
        verify=False,
        auth=httpx.DigestAuth("username", "password"),
        headers={"Content-Type": "application/json"},
        max_redirects=10,
        timeout=30
    )

    response = client.post(
        url= url,
        json=body,
        follow_redirects=True,
    )

    print(response.status_code, response.text)
```

I have compared this to the code, that i use with ``requests`` and the requests seems to be identical. I have looked up with Fiddler and saw a difference in the TLS encryption (``MD5`` vs ``SHA-256``). 

This is the result from the weekend. I will try again later.

**Comment by klacol** [comment]
Good to know. Unfortunately, we cannot use Postman in the integration. We need a httpx code snipped that works. Any help appreciated.

**Comment by klacol** [comment]
The code throws this error, but just with ``httpx``:

> Exception has occurred: RemoteProtocolError
> Server disconnected without sending a response.
> httpcore.RemoteProtocolError: Server disconnected without sending a response.

It is not really true, that the server does not send anything back. I see this, but I do not know what that means:

```
DEBUG:httpcore.http11:receive_response_headers.complete 
return_value=
(b'HTTP/1.1', 401, b'Unauthorized', 
[
    (
        b'WWW-Authenticate', 
        b'Digest realm="conexa-ETHE0300186023",
                qop="auth",
                algorithm=SHA-256,
                nonce="pDX9qihzjpcIIObgTyXsavIgCfU+6DCwXAJCAN3NAr0=",
                opaque="6QFXaqNNl1+PElXYIqA3FkUN6XU74ttID5zm2iuWDTE="'
    ), 
    (
        b'WWW-Authenticate', 
        b'Digest 
            realm="conexa-ETHE0300186023",
            qop="auth",
            algorithm=MD5,
            nonce="pDX9qihzjpcIIObgTyXsavIgCfU+6DCwXAJCAN3NAr0=",
            opaque="6QFXaqNNl1+PElXYIqA3FkUN6XU74ttID5zm2iuWDTE="'
    ), 
    (
        b'Content-Length', b'16'
    ), 
    (
        b'Content-Type', b'text/plain'
    )
])
```

A quick google search brings me to this error, which sound quite similar: https://github.com/encode/httpx/discussions/2056

**Comment by JosefinBerlin** [comment]
Meine Abfragen in postman funktionieren wie folgt:
Digest Auth mit Username und Password (MD5)
curl --location 'https://192.168.XXX200:443/smgw/m2m/<userid>.sm/json' 


Benutzt wird nicht die Identifikationsnummer ETHE......., sondern die ID des Kunden (userid) mit angefügtem .sm

**Comment by klacol** [comment]
When I connect with the python lib ``requests`` I also see the redirect to the long URI (--location). The redirect is made after calling just the URI ``https://192.168.XXX.XXX:443/smgw/m2m``. So no need to request the long URI.

But with ``httpx`` still no authentication for me with the aforementioned code snippet. Perhaps I oversee a simple bug in the code snippet?

**Comment by mbaeuerle** [comment]
> In my samples i use the lib [`requests`](https://pypi.org/project/requests/). The integration uses the lib [`httpx`](https://pypi.org/project/httpx/).
> 
> My connection with `requests` works like a charm. But I cannot figure it out, how to connect to the Theben Connexa SMGW with `httpx`.
> 
> I always get `01 Unauthorized`. I have tried to retrieve the the information of the SMGW with this code:
> 
>     # Request the smgw-info
>     url = "https://10.11.120.2/smgw/m2m"
>     username = "*****"
>     password = "*****"
>     body = {"method": "smgw-info"}
> 
>     client = httpx.Client(
>         verify=False,
>         auth=httpx.DigestAuth(username,password),
>         headers={"Content-Type": "application/json"},
>         max_redirects=10,
>         timeout=30
>     )
> 
>     response = client.post(
>         url= url,
>         json=body,
>         follow_redirects=True,
>     )
> 
>     print(response.status_code, response.text)
> 
> I have compared this to the code, that i use with `requests` and the requests seems to be identical. I have looked up with Fiddler and saw a difference in the TLS encryption (`MD5` vs `SHA-256`).
> 
> This is the result from the weekend. I will try again later.

Your snippet works for me and returns the correct response (using httpx version 0.28.1).

@jannickfahlbusch with the `json` fix proposed in the PR fetching the firmware version works for me:
```
2025-04-01 21:33:39.793 DEBUG (MainThread) [custom_components.ppc_smgw.config_flow] Connection Info called with {'meter_type': <Vendor.Theben: 'Theben'>}
2025-04-01 21:36:03.322 DEBUG (MainThread) [custom_components.ppc_smgw.config_flow] Connection Info called with {'name': 'test', 'host': 'https://192.168.xx.xx/smgw/m2m/xx.sm/json', 'username': 'xx', 'password': 'xx', 'scan_interval': 5, 'debug': False}
2025-04-01 21:36:03.322 DEBUG (MainThread) [custom_components.ppc_smgw.config_flow] user_input: {'name': 'test', 'host': 'https://192.168.xx.xx/smgw/m2m/xx.sm/json', 'username': 'xx', 'password': 'xx', 'scan_interval': 5, 'debug': False}
2025-04-01 21:36:03.322 DEBUG (MainThread) [custom_components.ppc_smgw] Vendor is: Vendor.Theben (<enum 'Vendor'>)
2025-04-01 21:36:03.322 DEBUG (MainThread) [custom_components.ppc_smgw] Initializing Theben client
2025-04-01 21:36:03.322 DEBUG (MainThread) [custom_components.ppc_smgw.coordinator] Fetching data from API
2025-04-01 21:36:03.322 INFO (MainThread) [custom_components.ppc_smgw] Getting data
2025-04-01 21:36:03.322 DEBUG (MainThread) [custom_components.ppc_smgw] Getting firmware version from https://192.168.xx.xx/smgw/m2m/xx.sm/json
2025-04-01 21:36:06.208 DEBUG (MainThread) [custom_components.ppc_smgw] Got firmware info response: 
Status code: 200
Raw response: {"elapsed-time":"37 miliseconds","method":"smgw-info","smgw-info":{"certificates":{"han":{"tls":"..."},"wan":[{"cert-index":"0","sig":"...","sub-ca":"..."},{"cert-index":"1","sig":"...","sub-ca":"..."}]},"firmware-info":{"component":"Firmware","hash":"1ff5dd3fce7a9c54ae07acaa089ad83713300c8824966901adafcca645f3547b","version":"v3.80.0-cc"},"smgw-id":"...","smgw-state":"...","smgw-time":"2025-04-01T21:36:05"},"version":"1.3.0"}
2025-04-01 21:36:06.208 DEBUG (MainThread) [custom_components.ppc_smgw] Returning information: Information(readings={}, firmware_version='v3.80.0-cc-1ff5dd3fce7a9c54ae07acaa089ad83713300c8824966901adafcca645f3547b', last_update=datetime.datetime(2025, 4, 1, 21, 36, 6, 208155))
2025-04-01 21:36:06.208 DEBUG (MainThread) [custom_components.ppc_smgw.coordinator] Finished fetching ppc_smgw data in 2.886 seconds (success: True)
```

**Comment by klacol** [comment]
I think, in my case it could be a problem with the network. I cannot change to IP of the smgw. But I cannot adapt my lan network to the network address of the smgw. So, I have installed a nat firewall (GL-MT300N-V2) that connects the smgw to our lan; perhaps there is a difference in the behavior of the packets in the two python libs. I will have to investigate the situation myself.

**Comment by klacol** [comment]
I have tried some hours; but no success to connect with ``httpx`` in my NAT situation. I have created a [simple script to test more easily](https://gist.github.com/klacol/d8b30cf0b08267c2366bed86b42302ee).

I managed to get rid of the security hints regarding the turned off TLS verification. I just download the public certificate als PEM file and then trust this certificate. I make the download via the IP Adress and then I read the name of the subject alternate name from the public certificate and use this name for the requests in the URL. The SAN is like this ``ethe0300186023.sm``. 

The certificate is only trusted, when the extension ``.sm`` ist used in the requests. Therefore i had to configure this as alias name for the IP address of the Theben Connexa in the DNS server in my network.

The requests with the library ``requests`` work still like a charm; and now with TLS verification. But the requests with ``httpx`` bring up now this error:

> DEBUG:httpcore.connection:start_tls.failed exception=ConnectError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)'))
> Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)

The specific problem wit httpx and the SSL context seems to be, that verify parameter in ``httpx`` actually works differently than with ``requests``.

**Comment by JosefinBerlin** [comment]
Hi @klacol ,
I'm having trouble with your guide above to integrate ha-ppc-smgw v0.0.12-alpha1 into HA, see #33 .
My SMGW is on the same network as HA (192.168.xxx.xxx) without a nat firewall. Maybe we could try your approaches with me. But I can't program. Do you have any idea how we could test it on me?

**Comment by klacol** [comment]
Hi @JosefinBerlin: You are lucky. My SMGW is on a different network and I cannot change to it. Unfortunately I myself cannot test the ha-ppc-smgw v0.0.12-alpha1 here at home. @mbaeuerle has confirmed that it works for him. So it should work also for you.

As of now, there is just one sensor implemented, asfaik, the request for the firmware version of the Theben Connexa. 

Have you updated the integration to the version ``v0.0.12-alpha1``?

![Image](https://github.com/user-attachments/assets/17244a7b-71bb-4106-afb1-4f5572c394c6)

Then you have to add the Smart Meter Gateway device like this. Does this work?

![Image](https://github.com/user-attachments/assets/5d668703-5511-4758-883b-70d5038a4c81)

Then the configuration of the url and the credentials should be like this:

![Image](https://github.com/user-attachments/assets/fc190700-8b3e-4fe6-b1bb-35f826fa746a)

![Image](https://github.com/user-attachments/assets/21d20006-9349-4769-a031-101f23a5e270)

But unfortunately, in my network, it does not work. I assume, because of an error in my side, since I even cannot connect with python ``httpx`` directly with the code above.

Hope this helps you.

**Comment by JosefinBerlin** [comment]
Hi @klacol ,

picture 1: done, ok
picture 2: done, ok
picture 3: done, ok

But then:

![Image](https://github.com/user-attachments/assets/eb60c76c-3080-4ef9-ac47-e73c1de09a65)

[ppc-log.txt](https://github.com/user-attachments/files/19823698/ppc-log.txt)

**Comment by JosefinBerlin** [comment]
Hallo @klacol,

the last few days I was a little bit frustrated because the error occurred. I have now involved my son and after some tinkering we have found a solution that works:
First, we adapted the URL according to the instructions from Theben:
URL: as specified by the metering point operator.
Port: as specified by the metering point operator
User name: as specified by the metering point operator.
Password: as specified by the metering point operator without (!) identification number (smgw-id)
To do this, the UserID is inserted into the full URL, which can be obtained according to A-2.1 of the instructions or via TruDi.
So the URL is accordingly:
https://{{URL}}:{{Port}}/smgw/m2m/{{userid}}.sm/json

But the error message still remained. So we looked at the file thebenconnexa.py in homeassistant/custom-components/ppc_smgw/gateways/theben/thebenconnexa/. The bug had to be sitting here somewhere, since postman provided the firmware version. The problem was in the lines from 50 (try:) Content-length is required ! So we added:
headers = {"Content-Length": "25"}

Voila!

![Image](https://github.com/user-attachments/assets/d325e156-9ff7-4d4b-917d-ca3700add11b)

**Comment by JosefinBerlin** [comment]
Hello @klacol,
have you already been able to solve your problem with the network and test the integration? Strangely enough, errors have occurred again recently. The solution with Content-length from line 50 did not work as expected. Sometimes the number was 17, sometimes 25. I didn't understand it. But now I've found a solution at @mbaeuerle:
On line 54, change **data**={"method": "smgw-info"} to **json**={"method": "smgw-info"}. Since then, everything has been ok.

**Comment by maximmustermann** [comment]
Hallo, für das Theben Gateway muss man als URL dann was eingeben? 

https://{{192.168.178.55}}:{{443}}/smgw/m2m/{{ETHE03xxxxxx}}.sm/json

so in der Art? 

Bei mir werden die Daten in der Integration überhaupt nicht gespeichert. Ich bin laut HACS auf der Version 0.12 alpha 
Angezeigt wird aber 0.0.010 unter Integrationen, die Abfrage zur Auswahl von Theben oder PPC erhalte ich allerdings. 


![Image](https://github.com/user-attachments/assets/0da0ddc2-fe51-46a2-b789-44fa13df7e51)

![Image](https://github.com/user-attachments/assets/4c2ed685-7d0f-4388-941d-fe430e0035df)

**Comment by LorbusChris** [comment]
ref https://github.com/jannickfahlbusch/ha-ppc-smgw/pull/40

**Comment by LorbusChris** [comment]
#40 is now fully functional. Please test and review!

**Comment by jannickfahlbusch** [comment]
I've just merged #40 into #33 and released [v0.0.13-alpha3](https://github.com/jannickfahlbusch/ha-ppc-smgw/releases/tag/v0.0.13-alpha3) with the changes. (Thank you for the contribution @LorbusChris!)

Could somebody of you test this version and report back?

**Comment by klacol** [comment]
Thank you @jannickfahlbusch and @LorbusChris . I am still struggling with my network. To solve this, I have bought an Raspberry PI to host a simple proxy service. The docu and the code is in this repo: https://github.com/klacol/smgw-proxy

I have tried it out with the Version v0.0.13-alpha3 auf this integration, but it is still not working for me. But I am coming nearer to my solution. Hopefully I will be "ready to test" some day  :-).

**Comment by LorbusChris** [comment]
For reference, this is the OpenWrt config I use on a Turris Omnia (can also be configured via LuCi Web UI):

`/etc/config/network`:
```
[snip]

config interface 'han'
	option proto 'static'`
	option ipaddr '192.168.137.1'
	option netmask '255.255.255.0'
	option enabled '1'
	option ipv6 '0'
	option device 'lan4'

```

`/etc/config/firewall`:
```
config zone 'han'
	option input 'REJECT'
	option output 'ACCEPT'
	option forward 'REJECT'
	option enabled '1'
	option name 'han'
	option masq '1'
	list network 'han'

config forwarding
	option src 'lan'
	option dest 'han'
```

**Comment by horstvogel** [comment]
Hello,
for me integration is not running. 
Which URL I need 

https://{{192.168.1.222}}/smgw/m2m/{{ETHE0300233614}}.sm/json

Thanks

**Comment by LorbusChris** [comment]
@klacol the URL you're using seems to be incomplete with the part after `m2m` missing (`/<ID>.sm/json`?

**Comment by horstvogel** [comment]
this is not working.

**Comment by LorbusChris** [comment]
My id looks a bit different there, without any prefixes and dashes. Have you tried including the han-user- prefix?

**Comment by horstvogel** [comment]
my komplett URL in the browser is something like this. 

https://192.168.1.222/smgw/cust/han-user-cfb58c6b-1817-4b5b-9611-3f3acf1491d.sm/start

it is different  to url in the integration for example /m2m/   in the Browser is /cust/

**Comment by horstvogel** [comment]
so you use the url you see in the browser?

**Comment by LorbusChris** [comment]
Try `https://192.168.1.222/smgw/m2m/han-user-cfb58c6b-1817-4b5b-9611-3f3acf1491d.sm/json` as instructed

**Comment by JosefinBerlin** [comment]
Here is my sensor from the configuration.yaml that works:
`sensor:
# Get Theben Conexa SMGW-ID A-2-2
  - platform: rest
    name: theben_conexa_smgw_id
    resource: https://<smgw-ip>:443/smgw/m2m/<Einspeisung-userid>.sm/json
    method: POST
    scan_interval: 600
    timeout: 30
    verify_ssl: false  # SMGW nutzt ein selbstsigniertes Zertifikat
    authentication: digest  # Digest-Auth aktivieren
    username: !secret smgw-Einspeisung-Username
    password: !secret smgw-Einspeisung-Password
    headers:
      Content-Type: application/json
    payload: '{"method": "smgw-info"}'
    json_attributes:
      - smgw-info
    value_template: 'ok'
`
Replace <smgw-ip> and <Einspeisung-userid> with the values communicated by the network operator.

**Comment by LorbusChris** [comment]
Going from the web ui url, I simply had to replace 'cust' with 'm2m' and 'start' with 'json'

**Comment by klacol** [comment]
> [@klacol](https://github.com/klacol) the URL you're using seems to be incomplete with the part after `m2m` missing (`/<ID>.sm/json`?

Thank you. My Code with the ``request`` lib works like a charm with the m2m-URL. The long URL is IMHO automatically reached via redirect. So  I do not understand, why this would not work with ``httpx``. There seems to be a different request handling in the libs.

<img width="638" height="228" alt="Image" src="https://github.com/user-attachments/assets/6b145e07-c0aa-4dcf-a49b-ea45921464f6" />

Nevertheless, I have tried [the direct URI](https://github.com/klacol/smgw-theben-conexa/blob/main/theben-conexa_httpx.py#L28), same error. The part after ``m2`` is in my case the username, that i got from my Messstellenbetreiber. I have double-checked it in the web ui of the SMGW.

**Comment by klacol** [comment]
> Hallo an alle, mir ist es mittlerweile gelungen, über postman von Theben Conexa 3.0 alle Informationen gemäß Schnittstellenbeschreibung A-2.1 bis A-2.7 zu erhalten

Ist Dein SMGW auf DHCP eingestellt?
