### ISSUE TITLE
Support for SMGW from EMH Metering

### ISSUE THREAD

**Issue by zdaniel10** [jannickfahlbusch/ha-ppc-smgw#56]
Hi,

I have a SMGW from EMH Metering. Is it possible to add support for that Smart Meter?

Daniel

**Comment by jannickfahlbusch** [comment]
Theoretically it should be possible.

[EHM states on their side](https://emh-metering.com/produkte/smart-meter-gateway/casa/) that the API documentation is available on request. I've sent them a mail asking for the documentation.

Without it we would need someone to reverse engineer the API or the communication before we can introduce it in this component

**Comment by zdaniel10** [comment]
That would be great. On the Website of the SMGW I have access to a JSON with the data… but didn’t succeed with a rest sensor until now.

**Comment by Pinky007** [comment]
Hej @iseeberg79 ,
Thank you for the try but it doesnt seems to work on my side.
The software that is suggested to be used by the network company (and work to read the data) is Trudi, you can find the source code here: https://bitbucket.org/dzgtrudi/trudi-public/src/master/

On my side, I tried to implement 3 different sensors after reading the logs.
With adress of the SMGW:
- 192.168.168.168
- http://192.168.168.168
- https://192.168.168.168

<img width="333" height="512" alt="Image" src="https://github.com/user-attachments/assets/b337f5c1-269b-4f5e-94d9-2633379c3f1d" />

But none of them seems to deliver any information:

<img width="691" height="465" alt="Image" src="https://github.com/user-attachments/assets/ac582646-23a6-461b-b7a8-a73d6af50d9e" />

For all 3

In the logs I can also see:

<img width="588" height="236" alt="Image" src="https://github.com/user-attachments/assets/ed23fda3-5961-4741-933b-bff941c64d05" />

<img width="599" height="269" alt="Image" src="https://github.com/user-attachments/assets/ec1d4d24-adaf-4033-9b5a-4a3d7b84058f" />

**Comment by Pinky007** [comment]
Continuing to look at it, seems that https unsigned seems to be the right way to go:

<img width="535" height="164" alt="Image" src="https://github.com/user-attachments/assets/31d39896-4314-42e3-a2fa-20e4e37feaec" />

At the root page of the device, it seems that the certificates can be found:

<img width="410" height="380" alt="Image" src="https://github.com/user-attachments/assets/e9e3f12a-a2b3-4e73-9ca1-31f57b018d8d" />

Client certificate is under address: https://192.168.168.168:10443/start
Signatur certificate is under: https://192.168.168.168/download/certificate.pem

The meter ID can be actually found under https://192.168.168.168/json/metering/origin/

<img width="527" height="158" alt="Image" src="https://github.com/user-attachments/assets/178864e4-f279-421a-8d5d-eb044199aae9" />

Which seems to give the expected numbers:

<img width="774" height="714" alt="Image" src="https://github.com/user-attachments/assets/c5452d5f-48b8-4ffe-8968-78d4e5703179" />

Edit:
https://192.168.168.168/json/metering/derived is covering the contracts for me seems to be 1FRO0161737863 (Tarifbezeichnung from Trudi)

Edit2: I tried to play around with the adresses in ppc_smgw/gateways/emh/emhcasa/emh_client.py without success :(
Any help is appraciated, i'm happy to help to test

**Comment by iseeberg79** [comment]
Thank you for testing. Yes, https://SMGW_IP is the way to go.
Found an issue. To strip the return values before parsing is missing. Preparing a PR to fix.

**Comment by iseeberg79** [comment]
Trudi is for analysis, imho. Irrelevant on gathering not aggregated meter values

**Comment by iseeberg79** [comment]
@Pinky007 could you do some tests?

**Comment by jannickfahlbusch** [comment]
I just released [v0.0.18](https://github.com/jannickfahlbusch/ha-ppc-smgw/releases/tag/v0.0.18) containing the fix

**Comment by Pinky007** [comment]
Hej @iseeberg79 , 
Sorry I didnt saw your merge request in the notifications yesterday.
I pulled the new release and it seems to work! :)

<img width="334" height="415" alt="Image" src="https://github.com/user-attachments/assets/cf68ab7f-8686-46f7-b724-ef891267adb9" />

Thank you!

I saw that in your original PR you mentioned
> I am able to gather more sensors, but this might not apply to all installations. I focused this change on the sensors implemented for other meters.

What kind of sensors are available? Do you have any list?
Didnt saw anything sexy to integrate from the Trudi interface but just checking :)

Thanks!

**Comment by iseeberg79** [comment]
I placed a test script and instructions with the PR in ./scripts - you could have a look. For me 18 sensors are shown with detailed info about realtime meter values (voltage&current per phase, actual power, etc)

**Comment by Pinky007** [comment]
Thank you,
Mine would read this: 
```
=== Result ===
Name:     EMH CASA
Model:    CASA
Firmware: Unknown
Updated:  2026-04-01 18:40:45.071632+00:00
Readings (13):
  1-0:1.8.0: 21457.672300000002
  1-0:2.8.0: 17274.479
  1-0:14.7.0: 49.800000000000004
  1-0:16.7.0: 39.0
  1-0:31.7.0: 1.46
  1-0:32.7.0: 235.20000000000002
  1-0:51.7.0: 1.36
  1-0:52.7.0: 233.70000000000002
  1-0:71.7.0: 1.44
  1-0:72.7.0: 233.70000000000002
  1-0:81.7.4: 56.0
  1-0:81.7.15: 104.0
  1-0:81.7.26: 91.0
```

But it doesnt seems that any fo the values are read through HA outside of 1.8.0 and 2.8.0.
All of those values seem to be base on standard OBIS description: https://oms-group.org/wp-content/uploads/2024/05/OMS-Spec_Vol2_AnnexA_F121.pdf
Is there a possibility to add them?
Thank you

**Comment by iseeberg79** [comment]
Cool. Yes, I know.  Value at 16.7.0 is actual power. It's a conceptual change, up to @jannickfahlbusch 

At this time I know only very few having that detailed metering available. But you proofed that it is available to others as well; EMH has enhanced the meter?

**Comment by Pinky007** [comment]
Not sure, but FYI, using Trudi (it's not showing in your above script reading), this is the fw version that I can read out of the smgw:

<img width="582" height="199" alt="Image" src="https://github.com/user-attachments/assets/91fbc770-110d-4ff8-8876-887a19ebd7ea" />

**Comment by jannickfahlbusch** [comment]
Hi all,

sorry for the late response due to vacation here.

I just fixed #96 with #102 which should allow intervals down to a poll every second. At least for PPC gateways this seems to be way too much leading to them in a locked up state. I am not sure if that is something solely on PPC gateways or if that has something to do with some compliance requirements.

We can for sure try to implement that for the EMH meters. Since I don't have one installed I would be unable to test higher frequency pools and would need to have someone test the changes. Due to lacking capacity this implementation might take some time sadly

**Comment by Pinky007** [comment]
Hej @jannickfahlbusch ,
Thanks for the info, however looking at the logs, data seems to be updated every 15min so I dont htink that it would make sense. Or @iseeberg79  are you pulling with shorter interval to get your Power?

What about the other fileds? @jannickfahlbusch , do you plan to have those other OBIS values pulled for PPC gateway as well? Ingo was saying that would need a conceptual change.
What do you  think?

**Comment by iseeberg79** [comment]
> Or @iseeberg79 are you pulling with shorter interval to get your Power?

I have an EMH Casa 1.1 smart meter installed. It's firmware allows gathering realtime values for the connected grid meter (EFR). I was not able to be sure on a profile being responsible but it seems not.

I am connecting once and then able to pull meter values for several OBIS codes (ex: 16.7.0 for actual power) until the authenticated session expires.

I know there are few systems providing realtime data, yet. Have read about innoxy and EMh recently.

https://www.inexogy.com/presse/spine-und-inexogy/

https://emh-metering.com/pressemitteilungen/emh-metering-neues-webportal-schafft-kundentransparenz-im-smart-meter-rollout/

**Comment by Pinky007** [comment]
Great to know, I also have a Casa1.1 so the same system should be possible. And I could test the implementation. Thanks for the links

**Comment by jannickfahlbusch** [comment]
Hi all,

I just merged the automatic OBIS value discovery from #171 (Implemented with AI help).

#174 activates this for EMH SMGWs. Would someone of you be able to test [this alpha version](https://github.com/jannickfahlbusch/ha-ppc-smgw/pull/174#issuecomment-5358641927)?

Thank you in advance!

**Comment by iseeberg79** [comment]
Hi @jannickfahlbusch,

I don't run Home Assistant myself, but I do have a real EMH CASA 1.1 gateway available, so I ran a raw dump against the underlying data path (via emh-casa-go) instead of the alpha build.

My installation currently exposes exactly 13 OBIS readings — the "core" set (total import/export energy, active power total + per phase, current per phase, voltage per phase, frequency: 1.8.0, 2.8.0, 16.7.0, 36.7.0, 56.7.0, 76.7.0, 31.7.0, 51.7.0, 71.7.0, 32.7.0, 52.7.0, 72.7.0, 14.7.0). No reactive power/energy, apparent power, power factor, or the 81.7.x codes @Pinky007 saw earlier — confirming that which OBIS codes a CASA gateway reports is meter/firmware-dependent, not fixed per gateway model.

Values were all plausible (230V, 49.9Hz, one phase at -154W = feed-in). I traced the discovery chain in #171/#174: emh_client.py builds readings as a dict[OBIS, Reading] from whatever logical_name entries the gateway response contains, and sensor.py's _build_dynamic_obis_sensors() iterates directly over data.readings to create entities — so it's genuinely driven by whatever codes are present, not a fixed catalog. Based on that and my raw dump, I'd expect it to correctly create sensors for those 13 codes on my install and nothing spurious for the ones I don't have.

I can't run the alpha build myself (no HA setup here), but happy to keep providing raw data dumps from the real gateway if that's useful.

Locally reported fetched meter values:
  2.8.0: 6726.60
  16.7.0: 4.00
  32.7.0: 230.00
  51.7.0: 1.43
  56.7.0: 104.00
  71.7.0: 0.91
  76.7.0: 53.00
  1.8.0: 2449.59
  14.7.0: 49.90
  31.7.0: 1.23
  36.7.0: -154.00
  52.7.0: 230.80
  72.7.0: 230.70

**Comment by Pinky007** [comment]
Thanks @iseeberg79 for the first tests.
I'm on vacation the next 3 weeks. I can test live when back :)
Thanks

**Comment by jannickfahlbusch** [comment]
Oh especially the 81.7.x codes were something I was not aware about. I'll add them to the library as well

**Comment by Pinky007** [comment]
Sorry for the delay in response but with the alpha1511, seems that more sensors are added:

<img width="851" height="728" alt="Image" src="https://github.com/user-attachments/assets/c7564a9f-0767-46fb-a69c-e075c2d3a71a" />

Firmware is still missing but this is not important.
From my point of view, could be merged

Let me know if you need specific tests or a new version with hte 81.7.x codes

**Comment by smhex** [comment]
Does TRUDI display the same sensors and values? I would love to integrate them into Home Assistant as well, but I am worried that my specific CASA smgw  might provide them.

btw: Firmware is available now with #179 ...

**Comment by jannickfahlbusch** [comment]
Great that the values can be retrieved now, I've therefore merged #174 and will release a new version this evening containing all of the changes :)

**Comment by jannickfahlbusch** [comment]
[v0.0.26](https://github.com/jannickfahlbusch/ha-ppc-smgw/releases/tag/v0.0.26) is now released containing the OBIS changes from #174 as well as #179 :) 

Thank you again for the testing @Pinky007  and the firmware version PR @smhex

**Comment by smhex** [comment]
@jannickfahlbusch : thanks for the release! Very nice. However, I still can't get any other values, the 1.8.0/2.8.0 and RSSI. My assumption is, that the availability of additional obis values depends on the configuration of the smgw, which is maintained by the operator. The additional sensor values are based on TAF10. The latter is not available on my smgw, neither via HA nor Trudi.

**Comment by jannickfahlbusch** [comment]
Yes, in case you are also not able to see them via Trudi there is nothing I can do. You would need to contact your grid operator to configure further values. However, from experience most of them won't configure additional ones though :/
